# Proxy server ports
ports:
  http: 11990
  https: 11991

# Rules for which packages to intercept
intercept:
  urlx: # Exclude url-s containing the following
    - .ico
    - .jpg
    - .jpeg
    - .png
    - .svg
    - .gif
    - .ttf
    - .otf
    - .js
    - .css
  contentType: # Show the received value from content (otherwise md5 hash)
    - text/plain
    - text/html
    - text/enriched
    - text/richtext
    - text/sgml
    - application/json

# Rules for modifying all intercepted packets
tamper:
  req: 
    header: # Modifying headers to a specific value, null means remove
      Connection: stay-alive
      Proxy-Connection: null
    body:
  res:
    header:
    body:
      - { rule: '{', replace: ??? }